# Dill issue #628

This repository contains a small example that causes [dill](https://github.com/uqfoundation/dill/) to raise an error `TypeError: 'NoneType' object is not iterable`. The issue is reported at https://github.com/uqfoundation/dill/issues/628

Run with a Python environment with dill installed:

```
git clone https://github.com/kelvinburke/dill-issue.git
cd dill-issue
python run.py
```
